# Generated by Django 2.2 on 2019-06-04 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateField(verbose_name='Data zakończenia')),
                ('is_used', models.BooleanField(default=False, verbose_name='Czy zakończone')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Czy zatwierdzone')),
                ('approver_user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='holiday_approver_user', to=settings.AUTH_USER_MODEL, verbose_name='Osoba zatwierdzająca')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='holiday_user', to=settings.AUTH_USER_MODEL, verbose_name='Pracownik')),
            ],
        ),
    ]
