# Generated by Django 2.2 on 2019-06-04 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_app', '0003_auto_20190604_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaymodel',
            name='approver_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='holiday_approver_user', to=settings.AUTH_USER_MODEL, verbose_name='Osoba zatwierdzająca'),
        ),
    ]
