# Generated by Django 2.2 on 2019-04-25 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.CharField(max_length=11, verbose_name='PESEL')),
                ('street', models.CharField(max_length=200, verbose_name='Ulica')),
                ('city', models.CharField(max_length=200, verbose_name='Miasto')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('post_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
    ]
