# Generated by Django 2.2 on 2019-05-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='uwagi'),
        ),
    ]
