# Generated by Django 2.2 on 2019-04-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofileinfo_house_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='image',
            field=models.ImageField(default=None, upload_to='avatars/'),
        ),
    ]
