# Generated by Django 2.2 on 2019-05-22 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190514_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=200, verbose_name='rfid')),
                ('comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='uwagi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_access', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='UserStateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_description', models.CharField(max_length=50, verbose_name='Stan użytkownika')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHoursModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Opis zmiany')),
                ('rate_of_pay', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Stawka płacy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_work_hours', to=settings.AUTH_USER_MODEL, verbose_name='Zmiana')),
            ],
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_manager',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_manager', to=settings.AUTH_USER_MODEL, verbose_name='Kierownik'),
        ),
        migrations.DeleteModel(
            name='UserAccess',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_state',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_state', to='accounts.UserStateModel', verbose_name='Stan użytkownika'),
        ),
    ]
