# Generated by Django 2.2 on 2019-05-22 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190522_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workhoursmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_work_hours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_work_hours', to='accounts.WorkHoursModel', verbose_name='Godziny pracy'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_manager', to=settings.AUTH_USER_MODEL, verbose_name='Kierownik'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_state',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_state', to='accounts.UserStateModel', verbose_name='Stan użytkownika'),
        ),
    ]
