# Generated by Django 2.2 on 2019-05-22 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190522_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_state', to='accounts.UserStateModel', verbose_name='Stan użytkownika'),
        ),
    ]
