# Generated by Django 2.2 on 2019-05-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190522_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatars/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='userstatemodel',
            name='state_description',
            field=models.CharField(max_length=500, verbose_name='Stan użytkownika'),
        ),
    ]
