# Generated by Django 2.2 on 2019-07-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance_exit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entranceexitmodel',
            name='end_date',
            field=models.DateTimeField(verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='entranceexitmodel',
            name='start_date',
            field=models.DateTimeField(verbose_name='Data rozpoczęcia'),
        ),
    ]
