# Generated by Django 2.2 on 2019-05-14 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('number', models.IntegerField(verbose_name='Numer projektu')),
                ('number_2', models.IntegerField(verbose_name='Numer projektu 2')),
                ('project_type', models.CharField(max_length=50, verbose_name='Typ projektu')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('contact', models.CharField(max_length=500, verbose_name='Kontakt')),
                ('commants', models.CharField(blank=True, max_length=500, null=True, verbose_name='Uwagi')),
                ('client_pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_pm_user', to=settings.AUTH_USER_MODEL, verbose_name='PM Klienta')),
                ('project_pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_pm_user', to=settings.AUTH_USER_MODEL, verbose_name='PM Projektu')),
            ],
        ),
    ]
