# Generated by Django 2.2 on 2019-07-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntranceExitModel',
        ),
        migrations.DeleteModel(
            name='EntranceExitReason',
        ),
    ]
