# Generated by Django 2.2 on 2019-06-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HolidayModel',
        ),
    ]
