# Generated by Django 2.2 on 2019-05-22 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0002_auto_20190522_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='id_employee',
            field=models.ManyToManyField(related_name='project_employee_user', to=settings.AUTH_USER_MODEL, verbose_name='Pracownik'),
        ),
    ]
