# Generated by Django 2.2 on 2019-05-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0003_auto_20190522_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaymodel',
            name='start_date',
            field=models.DateField(verbose_name='Data rozpoczęcia'),
        ),
    ]
