# Generated by Django 2.2 on 2019-05-23 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0008_auto_20190523_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automodel',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='automodel',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='entranceexitmodel',
            name='approver_user',
        ),
        migrations.RemoveField(
            model_name='entranceexitmodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='entranceexitmodel',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='entranceexitmodel',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='entranceexitmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='EntranceExitReason',
        ),
        migrations.RemoveField(
            model_name='resourcehistorymodel',
            name='approver_user',
        ),
        migrations.RemoveField(
            model_name='resourcehistorymodel',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resourcehistorymodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resourcemodel',
            name='approver_user',
        ),
        migrations.RemoveField(
            model_name='resourcemodel',
            name='resource_state',
        ),
        migrations.RemoveField(
            model_name='resourcemodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='holidaymodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='holiday_user', to=settings.AUTH_USER_MODEL, verbose_name='Pracownik'),
        ),
        migrations.DeleteModel(
            name='AutoModel',
        ),
        migrations.DeleteModel(
            name='EntranceExitModel',
        ),
        migrations.DeleteModel(
            name='FuelType',
        ),
        migrations.DeleteModel(
            name='ResourceHistoryModel',
        ),
        migrations.DeleteModel(
            name='ResourceModel',
        ),
        migrations.DeleteModel(
            name='ResourceStateModel',
        ),
    ]
