# Generated by Django 2.2 on 2019-05-23 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0010_auto_20190523_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcemodel',
            name='name',
            field=models.CharField(default=None, max_length=200, verbose_name='Nazwa zasobu'),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='brand',
            field=models.CharField(default=None, max_length=200, verbose_name='Marka zasobu'),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='model',
            field=models.CharField(default=None, max_length=200, verbose_name='Model zasobu'),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='resource_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resource_state', to='ems_app.ResourceStateModel', verbose_name='Stan zasobu'),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data przydzielenia'),
        ),
    ]
