# Generated by Django 2.2 on 2019-05-23 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0011_auto_20190523_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entranceexitmodel',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrance_exit_reason', to='ems_app.EntranceExitReason', verbose_name='Powód'),
        ),
    ]
