# Generated by Django 2.2 on 2019-05-23 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0012_auto_20190523_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entranceexitmodel',
            name='approver_user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrance_exit_approver_user', to=settings.AUTH_USER_MODEL, verbose_name='Osoba zatwierdzająca'),
        ),
    ]
