# Generated by Django 2.2 on 2019-05-23 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0013_auto_20190523_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entranceexitmodel',
            name='end_date',
        ),
        migrations.AddField(
            model_name='resourcemodel',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Czy dostępny'),
        ),
        migrations.AlterField(
            model_name='entranceexitmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrance_exit_project', to='ems_app.ProjectModel', verbose_name='Projekt'),
        ),
    ]
