# Generated by Django 2.2 on 2019-05-25 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0014_auto_20190523_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='id_project_pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_pm_user', to=settings.AUTH_USER_MODEL, verbose_name='Manager projektu'),
        ),
    ]
