# Generated by Django 2.2 on 2019-05-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0016_auto_20190525_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='commants',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Uwagi'),
        ),
    ]
